# Generated by Django 2.1.7 on 2019-05-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('urlSrc', models.TextField()),
                ('description', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
