# Generated by Django 2.1.7 on 2019-05-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uprofile',
            name='image',
            field=models.ImageField(default='empty', upload_to='images'),
        ),
    ]
